"""
Seed the Lakán DLSU-D Postgres database from the Firestore-export JSON files.

  python seed.py          → seed the database (idempotent, safe to re-run)
  python seed.py --sql    → print seed_data.sql instead (for Neon's editor)

Requires DATABASE_URL in the environment / .env (ignored for --sql).

Admin accounts created:
  * placeholder admin from ADMIN_EMAIL / ADMIN_PASSWORD (remove before pilot)
  * the owner account (aaf4837@dlsud.edu.ph) — hash only, password shared
    out-of-band; change via token-protected /api/admin/create any time.
"""

import json
import os

from dotenv import load_dotenv
from werkzeug.security import generate_password_hash

import db

load_dotenv()

LOCATIONS_FILE = 'firestore_locations_fixed.json'
PATHWAYS_FILE = 'firestore_pathways_fixed.json'

DEFAULT_ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'admin@lakan.local')
DEFAULT_ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'lakan-admin')

# Owner account (aaf4837@dlsud.edu.ph). Only the HASH lives in this repo —
# the password was shared with the owner out-of-band; change it any time via
# the token-protected /api/admin/create and replace this hash.
OWNER_ADMIN_EMAIL = 'aaf4837@dlsud.edu.ph'
OWNER_ADMIN_HASH = ("scrypt:32768:8:1$xpwLySZi5R5Ao4Cj$ddaa2714fc49978a9a66849fc"
                    "c7a76a2ad952a02da1ab18d371806e36410f656d3aa25658bd2be7f1f73"
                    "130fefd81b88d0ff0e67623392e772473240d0955890")

# Full display names for buildings whose Firestore export lost the `name`
# field — plus CEAT, whose export name is mislabeled "MLH".
# Sources: the old CAMPUS_DATA map in v1 app.py + MariaDB sample data.
# These take priority over the JSON. Unlisted entries fall back to their id.
KNOWN_NAMES = {
    'CEAT': 'College of Engineering, Architecture and Technology',
    'CBAA': 'College of Business Administration and Accountancy',
    'CTH': 'Candido Tirona Hall (High School)',
    'CTHM': 'College of Tourism and Hospitality Management',
    'JFH': 'Julian Felipe Hall',
    'Library': 'Aklatang Emilio Aguinaldo',
    'Square': 'Food Square',
    'Gate 1': 'Gate 1 (Main Entrance)',
}
# location_type overrides where the export lost them (old schema sample)
KNOWN_TYPES = {
    'Gate 1': 'gate', 'Gate 2': 'gate', 'Gate 3': 'gate', 'Gate 4': 'gate',
    'Square': 'service',
}


def sql_literal(v):
    """Render a Python value as a PostgreSQL literal."""
    if v is None:
        return 'NULL'
    if isinstance(v, bool):
        return 'TRUE' if v else 'FALSE'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def generate_sql() -> str:
    """Emit the whole seed as idempotent SQL (for Neon's web SQL editor)."""
    lines = [
        "-- ============================================================",
        "-- Lakán DLSU-D seed data — AUTO-GENERATED by `seed.py --sql`.",
        f"-- Placeholder admin: {DEFAULT_ADMIN_EMAIL.lower()} / ADMIN_PASSWORD",
        "-- Owner admin: aaf4837@dlsud.edu.ph (hash only).",
        "-- Safe to re-run (idempotent upserts).",
        "-- ============================================================",
        "BEGIN;",
    ]

    with open(LOCATIONS_FILE, 'r', encoding='utf-8') as f:
        locations = json.load(f)
    for loc in locations:
        lat, lng = loc['coordinates']
        name = KNOWN_NAMES.get(loc['id']) \
            or (loc.get('name') or loc.get('name ') or '').strip() \
            or loc['id']
        loc_type = loc.get('type') or KNOWN_TYPES.get(loc['id'], 'building')
        lines.append(
            "INSERT INTO locations (id, name, latitude, longitude, location_type, description) VALUES ("
            f"{sql_literal(loc['id'])}, {sql_literal(name)}, {lat}, {lng}, "
            f"{sql_literal(loc_type)}, {sql_literal(loc.get('description', ''))}) "
            "ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, latitude = EXCLUDED.latitude, "
            "longitude = EXCLUDED.longitude, location_type = EXCLUDED.location_type, "
            "description = EXCLUDED.description;"
        )

    with open(PATHWAYS_FILE, 'r', encoding='utf-8') as f:
        pathways = json.load(f)
    for pw in pathways:
        lines.append(
            "INSERT INTO pathways (id, name, pathway_type, surface, width, is_shaded, is_accessible) VALUES ("
            f"{sql_literal(pw['id'])}, {sql_literal(pw['name'])}, {sql_literal(pw.get('type', 'pedestrian'))}, "
            f"{sql_literal(pw.get('surface', 'concrete'))}, {float(pw.get('width', 2.0))}, "
            f"{sql_literal(bool(pw.get('shaded', False)))}, {sql_literal(bool(pw.get('accessible', True)))}) "
            "ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, pathway_type = EXCLUDED.pathway_type, "
            "surface = EXCLUDED.surface, width = EXCLUDED.width, is_shaded = EXCLUDED.is_shaded, "
            "is_accessible = EXCLUDED.is_accessible;"
        )
        lines.append(f"DELETE FROM pathway_points WHERE pathway_id = {sql_literal(pw['id'])};")
        for i, (lat, lng) in enumerate(pw['points']):
            lines.append(
                "INSERT INTO pathway_points (pathway_id, point_index, latitude, longitude) VALUES ("
                f"{sql_literal(pw['id'])}, {i}, {lat}, {lng});"
            )

    lines.append(
        "INSERT INTO admins (email, password, name) VALUES ("
        f"{sql_literal(DEFAULT_ADMIN_EMAIL.lower())}, "
        f"{sql_literal(generate_password_hash(DEFAULT_ADMIN_PASSWORD))}, 'Administrator') "
        "ON CONFLICT (email) DO NOTHING;"
    )
    lines.append(
        "INSERT INTO admins (email, password, name) VALUES ("
        + sql_literal(OWNER_ADMIN_EMAIL) + ", "
        + sql_literal(OWNER_ADMIN_HASH) + ", 'Lakan Owner') "
        + "ON CONFLICT (email) DO NOTHING;"
    )
    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


def seed_locations():
    with open(LOCATIONS_FILE, 'r', encoding='utf-8') as f:
        locations = json.load(f)

    for loc in locations:
        lat, lng = loc['coordinates']
        # The export is inconsistent: `name`, `'name '` (trailing space), or
        # missing entirely — KNOWN_NAMES wins over a wrong/missing export name.
        name = KNOWN_NAMES.get(loc['id']) \
            or (loc.get('name') or loc.get('name ') or '').strip() \
            or loc['id']
        loc_type = loc.get('type') or KNOWN_TYPES.get(loc['id'], 'building')
        rowcount = db.execute("""
            INSERT INTO locations (id, name, latitude, longitude, location_type, description)
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (id) DO UPDATE
                SET name = EXCLUDED.name,
                    latitude = EXCLUDED.latitude,
                    longitude = EXCLUDED.longitude,
                    location_type = EXCLUDED.location_type,
                    description = EXCLUDED.description
        """, (
            loc['id'], name, lat, lng, loc_type,
            loc.get('description', ''),
        ))
        status = "ok" if rowcount != -1 else "FAILED"
        print(f"  📍 {loc['id']:<28} {status}")

    return len(locations)


def seed_pathways():
    with open(PATHWAYS_FILE, 'r', encoding='utf-8') as f:
        pathways = json.load(f)

    for pw in pathways:
        with db.get_conn() as conn:
            if conn is None:
                print(f"  🛤️  {pw['id']:<28} FAILED (no DB)")
                continue
            with conn.cursor() as cur:
                cur.execute("""
                    INSERT INTO pathways (id, name, pathway_type, surface, width,
                                          is_shaded, is_accessible)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (id) DO UPDATE
                        SET name = EXCLUDED.name,
                            pathway_type = EXCLUDED.pathway_type,
                            surface = EXCLUDED.surface,
                            width = EXCLUDED.width,
                            is_shaded = EXCLUDED.is_shaded,
                            is_accessible = EXCLUDED.is_accessible
                """, (
                    pw['id'], pw['name'], pw.get('type', 'pedestrian'),
                    pw.get('surface', 'concrete'), pw.get('width', 2.0),
                    bool(pw.get('shaded', False)), bool(pw.get('accessible', True)),
                ))
                # Replace points so re-running the seed stays consistent
                cur.execute("DELETE FROM pathway_points WHERE pathway_id = %s", (pw['id'],))
                for i, (lat, lng) in enumerate(pw['points']):
                    cur.execute("""
                        INSERT INTO pathway_points (pathway_id, point_index, latitude, longitude)
                        VALUES (%s, %s, %s, %s)
                    """, (pw['id'], i, lat, lng))
        print(f"  🛤️  {pw['id']:<28} ok ({len(pw['points'])} points)")

    return len(pathways)


def seed_admin():
    email = DEFAULT_ADMIN_EMAIL.lower()
    rowcount = db.execute("""
        INSERT INTO admins (email, password, name)
        VALUES (%s, %s, %s)
        ON CONFLICT (email) DO NOTHING
    """, (email, generate_password_hash(DEFAULT_ADMIN_PASSWORD), 'Administrator'))

    if rowcount == -1:
        print("  🔑 admin                       FAILED (no DB)")
        return
    if rowcount == 0:
        print(f"  🔑 {email:<28} already exists (kept as-is)")
    else:
        print(f"  🔑 {email:<28} created (password from ADMIN_PASSWORD env)")

    rowcount = db.execute(
        "INSERT INTO admins (email, password, name) VALUES (%s, %s, %s) ON CONFLICT (email) DO NOTHING",
        (OWNER_ADMIN_EMAIL, OWNER_ADMIN_HASH, 'Lakan Owner'))
    print(f"  🔑 {OWNER_ADMIN_EMAIL:<32} {'created' if rowcount == 1 else 'already exists'}")


def main():
    if '--sql' in os.sys.argv:
        print(generate_sql(), end='')
        return

    print("=" * 60)
    print("  🌱 Lakán DLSU-D — database seeder")
    print("=" * 60)

    if db.init_pool() is None:
        print("❌ No DATABASE_URL set — nothing to seed. Fix .env first.")
        raise SystemExit(1)

    print("\n📍 Locations:")
    n_loc = seed_locations()

    print("\n🛤️  Pathways:")
    n_pw = seed_pathways()

    print("\n🔑 Admin accounts:")
    seed_admin()

    print(f"\n✅ Seeded {n_loc} locations and {n_pw} pathways.")


if __name__ == '__main__':
    main()
